### ISSUE TITLE
Andy's steps before releasing package

### ISSUE THREAD

**Issue by andrew-edwards** [pbs-assess/pacea#23]
- [x] For climate index importation (the comparing old to new), add an expect_equal check to make sure old values haven't changed. If they have then look into it manually (check the README associated with the data); implies we shouldn't really automate the updates as it would break the build if old data changed.
- [x] Finish importing climate indices, #10  - those are all done, issue contains future possible additions
- [x] Fix plotting issue for indices, #15  
- [x] Import buoy data from Andrea's scripts
- [x] Plotting functions for buoy data, based on Andrea's scripts
- [x] Write help files for the classes
- [x] Add Andrea's marine heat wave info
- [x] Plotting functions for single time series abstracted from spatiotemporal data - e.g. ROMS output at a specific location. Should probably be able to use existing plotting functions and just write a wrapper to extract the data and get in correct format 
- [x] Check testing up to date
- [x] Decide on #4
- [x] Check #13
- [x] Vignettes that cover as many functions as possible/reasonable, see #19 
- [x] Fix any remaining TODO's. Search the whole package: left a few minor ones left in data-raw/, R/. 
- [x] Get Travis (and maybe Kelsey or someone?) to look over vignettes, before pushing the .html 
- [x] Go through Travis's vignettes
- [x] Update author list
- [x] Add citation details (see sizeSpectra)
- [x] Update README
- [x] Add a version number, presumably 1.0.0 for first release
- [x] Start a NEWS to keep track of new features; decide how to do keep updated in practice (maybe when a commit does something major or adds a new feature).

**Comment by andrew-edwards** [comment]
- [ ] push .pdf of talk
- [ ] push .html's of vignettes, and link from README
- [ ] polish up README
