### ISSUE TITLE
Tasks todo before release

### ISSUE THREAD

**Issue by travistai2** [pbs-assess/pacea#27]
List of To Do items for Travis to get done before release

1. - [ ] Process ROMS data and upload to pacea-data
2. - [ ] Help files and functions for remaining ROMS data
3. - [ ] Ensure naming and numbering of ROMS data is appropriate for updating and searching in `get_pacea_data` function
4. - [ ] Vignette - Plotting for ROMS data; plot.pacea_st, ggplot2, plotting time series of data
5. - [ ] Vignette - Manipulating ROMS spatial data to format of interest
6. - [ ] Decide on including updating data in function for users to update. (e.g. prompt user to check for data updates and if available, whether they want to update)
7. - [ ] Decide on whether `pacea_data` object will include data that can be downloaded and data that is loaded with package

**Comment by andrew-edwards** [comment]
- [ ] I think we could do with a bit more info in the help files for the bccm outputs. Unless there is a master one they could all be linked to. For example `?bccm_all_variables` doesn't really give much (e.g. even the acronym definition of bccm). I know we will tell people to work through the vignettes first (and don't want to repeat too much information), but I think the help files should have more info. Or maybe I'm missing something.

**Comment by andrew-edwards** [comment]
- [ ] Also, I can't find the function to just download all the bccm data (have been meaning to do that for a while). Suggest including it in some help files, and also putting it more up front in the vignette. Most people will want to just download everything in one go I expect, to save waiting later (plus the results aren't going to be constantly updated). 
- [ ] I think you were okay with the shortened text I did at the start of the bccm text, so I'll take out the original text (it's still there). (I still have some edits I might do to the vignette, but focussing on talk for now).
